import a bunch of goad fixes from other projects.

diff --git a/goad b/goad
--- a/goad
+++ b/goad
@@ -1,11 +1,11 @@
 #!/bin/bash
+set -e
 
-# Where is this script located?
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-cd "$DIR"
+# Set up gopath.  Autodetect go install if necessary.
+cd "$( dirname "${BASH_SOURCE[0]}" )"
+[ -z "$GOROOT" ] && GOROOT="$(dirname "$(which go)")/../"
+export GOROOT
 export GOPATH="$PWD"/.gopath/
-export BASEDIR="$PWD"
-
 
 # subsection arg?
 [ -z "$2" ] && SUBSECTION="./..." || SUBSECTION="./$2"
@@ -15,8 +15,29 @@ export BASEDIR="$PWD"
 pkg="polydawn.net/grypt"
 name="grypt"
 
-
-case "$1" in
+if [ -z "$1" ] ; then
+	(
+		go fmt "$SUBSECTION"
+		go install "$pkg" && {
+			echo -e "\E[1;32minstall successful.\E[0;m\n"
+		} || {
+			echo -e "\E[1;41minstall failed!\E[0;m"
+			exit 8
+		}
+		go test "$SUBSECTION" && {
+			echo -e "\n\E[1;32mall tests green.\E[0;m"
+		} || {
+			echo -e "\n\E[1;41msome tests failed!\E[0;m"
+			exit 4
+		}
+	)
+else
+	case "$1" in
+	-)
+		# passthrough for other commands
+		shift
+		go "$@"
+		;;
 	env)
 		echo "GOROOT=`go env GOROOT`"
 		echo "GOPATH=`go env GOPATH`"
@@ -29,38 +50,56 @@ case "$1" in
 		# (we don't do it at the front of every build because it will move submodules if you already have them, and that might not be what you want as you're plowing along)
 		git submodule update --init
 		;;
-	build)
-		go build
-		;;
 	test)
-		go test -i "$SUBSECTION" &&
-		go test -v "$SUBSECTION"
+		set +e ; shift ; shift ; set -e
+		go test -i "$SUBSECTION" "$@" &&
+		go test -v "$SUBSECTION" "$@" && {
+			echo -e "\n\E[1;32mall tests green.\E[0;m"
+		} || {
+			echo -e "\n\E[1;41msome tests failed!\E[0;m"
+			exit 4
+		}
 		;;
 	install)
-		go install $pkg
+		go install "$pkg"
 		;;
 	fmt)
 		go fmt "$SUBSECTION"
 		;;
 	doc)
-		[ -z "$2" ] && packages=`for dir in */; do find "$dir" -type d; done` || packages="$2"
-		for package in $packages; do
+		for package in $(go list "$SUBSECTION" | sed "s#^_${PWD}#${pkg}#"); do
 			echo -e "==== $package ====\n"
-			godoc $pkg/$package
+			godoc "$package"
 			echo -e "\n\n\n"
 		done
 		;;
 	convey)
-		go install github.com/smartystreets/goconvey && "$GOPATH"/bin/goconvey
+		shift
+		go install github.com/smartystreets/goconvey && "$GOPATH"/bin/goconvey "$@"
 		;;
 	cover)
-		for package in `go list ./... | sed "s#^_${PWD}#${pkg}#"` ; do rm -f cover.out ; (echo ==== ; (go test -coverprofile=cover.out $package) && echo ---- && go tool cover -func=cover.out && echo ---- && go tool cover -html=cover.out ; echo ====); done
-		rm -f cover.out
+		coverFile="$GOPATH/tmp/cover/cover.out"
+		mkdir -p "$(dirname "$coverFile")"
+		for package in $(go list "$SUBSECTION" | sed "s#^_${PWD}#${pkg}#"); do
+			rm -f "$coverFile"
+			echo "==== $package ===="
+			go test -coverprofile="$coverFile" "$package" && \
+			[ -f "$coverFile" ] && \
+			echo ---- && \
+			go tool cover -func="$coverFile" && \
+			echo ---- && \
+			go tool cover -html="$coverFile"
+			echo ====
+			echo
+		done
+		rm -f "$coverFile"
+		;;
+	clean)
+		rm -rf "$GOPATH/bin" "$GOPATH/pkg" "$GOPATH/tmp"
 		;;
 	*)
-		echo "Usage: $0 {init|build|test|install|fmt|doc}" 1>&2;
+		echo "Usage: $0 {init|test|install|fmt|doc|cover|clean}" 1>&2;
 		exit 1
 	;;
-esac
-
-
+	esac
+fi
